### ISSUE TITLE
Issue during reproducibility 

### ISSUE THREAD

**Issue by afuskelay** [aleflabo/HypAD#1]
Thank you for sharing the code publicly and your work on this crucial issue for senior citizens.
I would like to replicate the findings you reported in the study, however I can find no information regarding the experimental setup. I attempted to run the code with Python 3.9, but I encountered an issue. After some renaming and adjusting, it began to produce errors. Please help me by sharing the setup file. Additionally, will you kindly verify that the code that was pushed is working code?

Thanks 
Aayush Fuskelay

**Comment by aleflabo** [comment]
Hi Aayush,

We're working on the final and official version to solve some bugs in the code at the moment in the repo. 

We'll make sure to update you as soon as it's ready.

**Comment by aleflabo** [comment]
Hi @aayush1991,

I've updated the repo and added the environment I used for this project. At the moment is not possible to download the univariate datasets from the official repo. I hope the problem gets solved soon. You can track the issue [here](https://github.com/sintel-dev/Orion/issues/415)
